sudo: false
dist: xenial

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry


language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8-dev"
    - python: "pypy3"

allow_failures:
  - python: "pypy-3.6"
  - python: "3.8-dev"


install:
  - pip install -U pip
  - pip install tox-travis

script: tox
