sudo: false
dist: xenial
language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8-dev"
    - python: "pypy3"

allow_failures:
  - python: pypy3

install:
  - pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script: poetry run pytest --cov=zeitig --cov-config=.coveragerc tests/ -W ignore
