sudo: false
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3.6"

install:
  - pip install -U pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v

script: poetry run pytest --cov=zeitig --cov-config=.coveragerc tests/ -W ignore
